# Generated by Django 6.1 on 2026-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0002_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='traitement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
