# Generated by Django 6.1 on 2026-08-23 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0003_enfant_traitement'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSymptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('symptome', models.CharField(max_length=200)),
                ('intensite', models.CharField(choices=[('faible', 'Faible'), ('moderee', 'Modérée'), ('forte', 'Forte'), ('tres_forte', 'Très forte')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('traitement_pris', models.TextField(blank=True)),
                ('evolution', models.CharField(blank=True, choices=[('ameliore', 'Amélioration'), ('stable', 'Stable'), ('aggrave', 'Aggravation')], max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_symptomes', to='sante.enfant')),
            ],
        ),
    ]
