# Generated by Django 6.1 on 2026-08-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0004_journalsymptome'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalsymptome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='journalsymptome',
            name='date',
            field=models.DateField(),
        ),
    ]
