# Generated by Django 6.1 on 2026-08-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0005_journalsymptome_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=1, max_digits=4)),
                ('date_prise', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='sante.enfant')),
            ],
            options={
                'verbose_name': 'Température',
                'verbose_name_plural': 'Températures',
                'ordering': ['-date_prise'],
            },
        ),
    ]
