# Generated by Django 6.1 on 2026-08-26 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0006_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSymptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='symptomes/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sante.journalsymptome')),
            ],
        ),
    ]
