# Generated by Django 6.1 on 2026-08-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0007_photosymptome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=150)),
                ('dose', models.CharField(help_text='Exemple : 1 pipette de 5 ml', max_length=100)),
                ('frequence', models.CharField(choices=[('unique', 'Une seule fois'), ('quotidienne', 'Une fois par jour'), ('2_jours', 'Deux fois par jour'), ('3_jours', 'Trois fois par jour'), ('4_jours', 'Quatre fois par jour'), ('6_heures', 'Toutes les 6 heures'), ('8_heures', 'Toutes les 8 heures'), ('12_heures', 'Toutes les 12 heures'), ('personnalisee', 'Personnalisée')], max_length=30)),
                ('intervalle_heures', models.PositiveIntegerField(blank=True, help_text='Délai minimal entre deux prises, en heures', null=True)),
                ('premiere_prise', models.DateTimeField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('prochaine_prise', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='sante.enfant')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
                'ordering': ['prochaine_prise', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PriseTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_prevue', models.DateTimeField()),
                ('date_heure_prise', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('prise', 'Prise effectuée'), ('annulee', 'Annulée'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises', to='sante.traitement')),
            ],
            options={
                'verbose_name': 'Prise de traitement',
                'verbose_name_plural': 'Prises de traitement',
                'ordering': ['-date_heure_prevue'],
            },
        ),
    ]
