# Generated by Django 6.1 on 2026-08-27 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0008_traitement_prisetraitement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartageEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_invitation', models.DateTimeField(auto_now_add=True)),
                ('accepte', models.BooleanField(default=False)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='sante.enfant')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants_partages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('enfant', 'parent')},
            },
        ),
    ]
