# Generated by Django 6.1 on 2026-08-28 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0009_partageenfant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalsymptome',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
