# Generated by Django 6.1 on 2026-08-28 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0010_alter_journalsymptome_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_gardien', models.CharField(max_length=150)),
                ('telephone_gardien', models.CharField(max_length=30)),
                ('type_gardien', models.CharField(choices=[('baby_sitter', 'Baby-sitter'), ('grand_parent', 'Grand-parent'), ('autre', 'Autre')], max_length=30)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('partager_allergies', models.BooleanField(default=True)),
                ('partager_traitement', models.BooleanField(default=True)),
                ('partager_alimentation', models.BooleanField(default=True)),
                ('partager_sommeil', models.BooleanField(default=True)),
                ('partager_antecedents', models.BooleanField(default=False)),
                ('partager_vaccinations', models.BooleanField(default=False)),
                ('partager_consultations', models.BooleanField(default=False)),
                ('partager_contact_parent', models.BooleanField(default=True)),
                ('consignes', models.TextField(blank=True, null=True)),
                ('contact_urgence', models.CharField(blank=True, max_length=30, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes_garde', to='sante.enfant')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes_garde_crees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
