# Generated by Django 6.1 on 2026-08-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0011_modegarde'),
    ]

    operations = [
        migrations.AddField(
            model_name='modegarde',
            name='partager_hydratation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modegarde',
            name='partager_temperature',
            field=models.BooleanField(default=False),
        ),
    ]
